# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  vmImage: ubuntu-latest

stages:
  - stage: teststage
    displayName: 'test-stage to see script execution'
    jobs:
      - job: validate
        workspace:
          clean: all
        steps:
        - script: |
            cd GCP-Infra
            ls
        - task: TerraformTaskV4@4
          inputs:
            provider: 'gcp'
            command: 'init'
            workingDirectory: './GCP-Infra'
            backendServiceGCP: 'tf-gcp-sa-resource'
            backendGCPBucketName: 'terraform-storage-bucket-siva'



